<<<<<<< HEAD
# Generated by Django 3.2.12 on 2022-09-23 15:42
=======
# Generated by Django 3.2.12 on 2022-09-20 22:30
>>>>>>> bfbc94f6430148971d6f9eb81481b1860adc320a

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('cow_num', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('group', models.CharField(default='new_cow', max_length=50)),
                ('stats', models.CharField(max_length=50)),
                ('carving_num', models.IntegerField(default=0)),
                ('age', models.IntegerField()),
                ('empyt_days', models.IntegerField(blank=True, null=True)),
                ('birthday', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estrus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_estrus', models.IntegerField()),
                ('after_fertilization', models.IntegerField()),
                ('estrus_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pre_childbirth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy_days', models.IntegerField()),
                ('pre_childbirth', models.DateTimeField()),
                ('fertilization_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorID',
            fields=[
                ('sensor_serial', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('sensor_ver', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
<<<<<<< HEAD
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('_id', models.CharField(max_length=50)),
=======
                ('_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
>>>>>>> bfbc94f6430148971d6f9eb81481b1860adc320a
                ('sensor_ver', models.CharField(max_length=50)),
                ('msg_ver', models.IntegerField()),
                ('macAddr', models.CharField(max_length=50)),
                ('battery', models.FloatField()),
                ('temp', models.FloatField()),
                ('hpa', models.FloatField()),
                ('acc_x', models.IntegerField()),
                ('acc_y', models.IntegerField()),
                ('acc_z', models.IntegerField()),
                ('vector', models.IntegerField()),
                ('rssi', models.FloatField()),
                ('time', models.CharField(max_length=50)),
                ('packetnum', models.IntegerField()),
                ('kr_time', models.CharField(max_length=50)),
<<<<<<< HEAD
                ('sensor_ID', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SensorID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_serial', models.CharField(max_length=50, unique=True)),
                ('sensor_ver', models.CharField(max_length=50)),
=======
                ('sensor_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cow.sensorid')),
>>>>>>> bfbc94f6430148971d6f9eb81481b1860adc320a
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField()),
                ('event_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cow.cow')),
            ],
        ),
        migrations.AddField(
            model_name='cow',
<<<<<<< HEAD
            name='SensorID_id',
=======
            name='sensorID',
>>>>>>> bfbc94f6430148971d6f9eb81481b1860adc320a
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cow.sensorid'),
        ),
    ]
