# Generated by Django 3.2.12 on 2022-09-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Neck_sensor',
        ),
    ]
