# Generated by Django 3.2.12 on 2022-09-12 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0005_auto_20220912_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cow',
            name='sensor_id',
        ),
        migrations.DeleteModel(
            name='sensor',
        ),
    ]
