# Generated by Django 3.2.12 on 2022-09-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0006_auto_20220912_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_ver', models.CharField(max_length=50)),
                ('msg_ver', models.IntegerField()),
                ('sensor_num', models.CharField(max_length=50)),
                ('macAddr', models.CharField(max_length=50)),
                ('battery', models.FloatField()),
                ('temp', models.FloatField()),
                ('hpa', models.FloatField()),
                ('acc_x', models.IntegerField()),
                ('acc_y', models.IntegerField()),
                ('acc_z', models.IntegerField()),
                ('vector', models.IntegerField()),
                ('rssi', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('packetnum', models.CharField(max_length=50)),
                ('kr_time', models.DateTimeField()),
            ],
        ),
    ]
