# Generated by Django 3.2.12 on 2022-09-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0007_sensor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
