# Generated by Django 3.2.12 on 2022-09-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0009_sensor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cow',
            name='childbirth_id',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='estrus_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='cid',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='cow',
        ),
        migrations.DeleteModel(
            name='estrus',
        ),
        migrations.DeleteModel(
            name='event',
        ),
        migrations.DeleteModel(
            name='pre_childbirth',
        ),
    ]
