# Generated by Django 3.2.12 on 2022-09-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0011_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
