# Generated by Django 3.2.12 on 2022-09-12 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cow', '0013_auto_20220912_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_num', models.CharField(max_length=50, unique=True)),
                ('group', models.CharField(default='new_cow', max_length=50)),
                ('stats', models.CharField(max_length=50)),
                ('carving_num', models.IntegerField(default=0)),
                ('age', models.IntegerField()),
                ('postpartal_days', models.IntegerField(blank=True, null=True)),
                ('empyt_days', models.IntegerField()),
                ('birthday', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Estrus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_estrus', models.IntegerField()),
                ('after_fertilization', models.IntegerField()),
                ('estrus_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pre_childbirth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy_days', models.IntegerField()),
                ('pre_childbirth', models.DateTimeField()),
                ('fertilization_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=50)),
                ('sensor_ver', models.CharField(max_length=50)),
                ('msg_ver', models.IntegerField()),
                ('sensorID', models.CharField(max_length=50)),
                ('macAddr', models.CharField(max_length=50)),
                ('battery', models.FloatField()),
                ('temp', models.FloatField()),
                ('hpa', models.FloatField()),
                ('acc_x', models.IntegerField()),
                ('acc_y', models.IntegerField()),
                ('acc_z', models.IntegerField()),
                ('vector', models.IntegerField()),
                ('rssi', models.FloatField()),
                ('time', models.CharField(max_length=50)),
                ('packetnum', models.IntegerField()),
                ('kr_time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField()),
                ('event_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cow.cow')),
            ],
        ),
        migrations.AddField(
            model_name='cow',
            name='childbirth_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cow.pre_childbirth'),
        ),
        migrations.AddField(
            model_name='cow',
            name='estrus_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cow.estrus'),
        ),
    ]
