# Generated by Django 3.2.12 on 2022-09-13 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0014_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='sensorid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cow.sensor'),
        ),
    ]
