# Generated by Django 3.2.12 on 2022-09-14 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cow', '0015_cow_sensorid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cow',
            old_name='sensorid',
            new_name='sensorID',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='postpartal_days',
        ),
        migrations.AddField(
            model_name='cow',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cow',
            name='empyt_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
