# Generated by Django 3.2.12 on 2022-09-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0017_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='cow',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
