# Generated by Django 3.2.12 on 2022-09-14 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cow', '0018_auto_20220914_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('cow_num', models.CharField(default=1, max_length=50, unique=True)),
                ('group', models.CharField(default='new_cow', max_length=50)),
                ('stats', models.CharField(max_length=50)),
                ('carving_num', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=1)),
                ('empyt_days', models.IntegerField(blank=True, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
