# Generated by Django 3.2.12 on 2022-09-14 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0019_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sensorID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cow.sensor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='birthday',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
