# Generated by Django 3.2.12 on 2022-09-14 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0020_auto_20220914_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='childbirth_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cow.pre_childbirth'),
        ),
        migrations.AddField(
            model_name='post',
            name='estrus_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cow.estrus'),
        ),
    ]
