# Generated by Django 3.2.12 on 2022-09-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0022_auto_20220915_0006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
