# Generated by Django 3.2.12 on 2022-09-15 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0023_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='childbirth_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cow.pre_childbirth'),
        ),
        migrations.AddField(
            model_name='cow',
            name='estrus_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cow.estrus'),
        ),
        migrations.AlterField(
            model_name='cow',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cow',
            name='birthday',
            field=models.DateTimeField(),
        ),
    ]
