# Generated by Django 3.2.12 on 2022-09-19 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0024_auto_20220915_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorSN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_Serial', models.CharField(max_length=50, unique=True)),
                ('sensor_ver', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cow',
            name='author',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='childbirth_id',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='estrus_id',
        ),
        migrations.AlterField(
            model_name='cow',
            name='birthday',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cow',
            name='sensorID',
            field=models.ForeignKey(db_column='sensorID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cow.sensor'),
        ),
    ]
